version: "3.9"

services:
  db:
    volumes:
      - ~/data/lenslocked/psql:/var/lib/postgresql/data/pgdata
      # mounts a volume defined in ~/data/lenslocked/psql in the usually defined space for a volume
      # within the docker container in production
  caddy:
    image: caddy
    restart: always
    ports:
      - 80:80
      - 443:443
      # - "443:443/udp"
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile
  server:
    build:
      context: ./
      dockerfile: Dockerfile
    restart: always
    volumes:
      - ./images:/app/images
    ports:
      - 3000:3000
    depends_on:
      - db
